SELECT TOP (1000) 
--[preMarketChange]
     -- ,[preMarketChangePercent]
--,[preMarketPrice]
    --  ,[preMarketTime]
    --  ,[postMarketChange]
     -- ,[postMarketChangePercent]
    --  ,[postMarketPrice]
    --  ,[postMarketTime]
      --,[language]
      [region]
      ,[quoteType]
      ,[typeDisp]
      --,[quoteSourceName]
      --,[triggerable]
      ,[customPriceAlertConfidence]
      ,[currency]
    --  ,[exchange]
     -- ,[shortName]
      --,[longName]
     -- ,[messageBoardId]
    --  ,[exchangeTimezoneName]
     -- ,[exchangeTimezoneShortName]
    --  ,[gmtOffSetMilliseconds]
      --,[market]
     -- ,[esgPopulated]
      ,[regularMarketChangePercent]
      ,[regularMarketPrice]
      ,[marketState]
      ,[regularMarketChange]
      --,[regularMarketTime]
      ,[regularMarketDayHigh]
      --,[regularMarketDayRange]
      ,[regularMarketDayLow]
      ,[regularMarketVolume]
    --  ,[regularMarketPreviousClose]
   --   ,[bid]
     -- ,[ask]
     -- ,[bidSize]
     -- ,[askSize]
     -- ,[fullExchangeName]
   --   ,[financialCurrency]
      ,[regularMarketOpen]
     -- ,[averageDailyVolume3Month]
      --,[averageDailyVolume10Day]
     -- ,[fiftyTwoWeekLowChange]
      --,[fiftyTwoWeekLowChangePercent]
    --  ,[fiftyTwoWeekRange]
     -- ,[fiftyTwoWeekHighChange]
     -- ,[fiftyTwoWeekHighChangePercent]
     -- ,[fiftyTwoWeekLow]
     -- ,[fiftyTwoWeekHigh]
--,[fiftyTwoWeekChangePercent]
      ,[dividendDate]
   --   ,[earningsTimestamp]
     -- ,[earningsTimestampStart]
     -- ,[earningsTimestampEnd]
     -- ,[earningsCallTimestampStart]
      --,[earningsCallTimestampEnd]
      --,[isEarningsDateEstimate]
     -- ,[trailingAnnualDividendRate]
     -- ,[trailingPE]
    --  ,[dividendRate]
    --  ,[trailingAnnualDividendYield]
    --  ,[dividendYield]
     -- ,[epsTrailingTwelveMonths]
     -- ,[epsForward]
      --,[epsCurrentYear]
      --,[priceEpsCurrentYear]
      --,[sharesOutstanding]
      ,[bookValue]
--,[fiftyDayAverage]
   --   ,[fiftyDayAverageChange]
--,[fiftyDayAverageChangePercent]
      --,[twoHundredDayAverage]
    --  ,[twoHundredDayAverageChange]
     -- ,[twoHundredDayAverageChangePercent]
    -- ,[marketCap]
     -- ,[forwardPE]
      ,[priceToBook]
     -- ,[sourceInterval]
     -- ,[exchangeDataDelayedBy]
    --  ,[averageAnalystRating]
     -- ,[hasPrePostMarketData]
     -- ,[firstTradeDateMilliseconds]
      --,[priceHint]
      --,[tradeable]
      --,[cryptoTradeable]
     -- ,[displayName]
    --  ,[symbol]
  FROM [AdventureWorksDW2022].[dbo].[API_MARKET_QUOTES]
